version: '3'

services:
  app:
    image: olx_bot
    container_name: olx_bot
    ports:
      - "80:80"
    networks:
      - webnet

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
      - "80:80"
    depends_on:
      - app
    networks:
      - webnet

networks:
  webnet:
